### ISSUE TITLE
Errors after selecting parts in LiveEdit 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-features#110]
Case 1 
1.  Open Features, open Page Component View and insert part component
 2. Select  `Audit Logs Demo`  
**BUG - 500 error appears:**

![image](https://user-images.githubusercontent.com/3728712/82455380-9229db80-9abb-11ea-94e7-982d740b120f.png)

Case 2 
1. Select  `Http Lib example` part

![image](https://user-images.githubusercontent.com/3728712/82455695-e7fe8380-9abb-11ea-9ac0-0af42fb0dbda.png)

Case 3 

Select `Schedule-publish` part:

![image](https://user-images.githubusercontent.com/3728712/82455910-390e7780-9abc-11ea-83a8-8d279d7afb97.png)

**Comment by alansemenov** [comment]
We already have a bug for case 3: https://github.com/enonic/app-features/issues/108

It shouldn't be fixed here.
