### ISSUE TITLE
app-features is not using Gradle 5

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-features#82]
App needs to be updated to build with Gradle 5

**Comment by alansemenov** [comment]
Why this task? None of our apps are using Gradle 5 at the moment and this should be done for the XP and its bundled repos first and then for all other apps.

**Comment by sigdestad** [comment]
It's a reminder. And the sooner we have tested gradle 5, the better?

**Comment by alansemenov** [comment]
done
